# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Henning Vespermann
title: Senior Software Engineer
email: henning.luenser@gmail.com
website: https://cv.hlnr.de/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: CaptainStandby
xing_username: Henning_Vespermann2

# Additional icon links
additional_links:
- title: gitlab.com
  icon: fab fa-gitlab
  url: https://gitlab.com/hlnr

# About Section
about_title: About Me
# about_profile_image: images/profile.jpg
about_content: >
  Hi, my name's Henning and I'm a senior software engineer.
  I have extensive experience developing, delivering and operating cloud native applications.
  My work covered multifaceted projects providing me with comprehensive teamwork and
  technology skills as well as deep insights in requirements analysis.

  I'm most skilled in C#, Kubernetes, Azure.

  My motivation comes from learning new things, expanding my skill set and solving difficult problems.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: EyeC GmbH
        link: https://www.eyec.com/
        link_text: eyec.com
        sub_title: Senior Software Engineer
        caption: 2017 - Present
        description: |
          Design and implementation of a cloud native web application deployed using Kubernetes (Azure AKS).
          - Responsibility for overall system architecture, business logic and operations.
          - Established a continuous delivery pipeline using Azure DevOps, GitOps, ArgoCD and infrastructure as code (IaC).
          - Advocating for clean code, modular and robust software design aimed at high productivity and fast product delivery.
          - Leading the project to rebuild the frontend as a single-page application using .NET Core, Vue.js and TypeScript.
          - Designing and implementing an event sourcing framework in .NET Core
          - Implementing a GraphQL-API Gateway in Typescript utilizing gRPC for backend communication.

      - layout: left
        title: EyeC GmbH
        link: https://www.eyec.com/
        link_text: eyec.com
        sub_title: Software Engineer
        caption: March 2010 - 2016
        quote: >
          Founded in 2002 in Hamburg, Germany, EyeC is the market leader for quality
          control throughout the entire printing process.
          EyeC employs state of the art image processing algorithms to detect differences
          and missprints in packaging of pharmaceutical and other products.

        description: |
          I was responsible for all aspects of software design, development and architecture using C#, C++ and other languages and technologies
          - Expansion and evolution of a C++ MFC based application using C++/CLI and C#.
          - Serving customers primarily from the pharmaceutical industry and expanding the software with respect to strict industry standards and regulations.
          - Developed and maintained build pipelines using SVN, MSBuild and CruiseControl.NET.

      - title: Daedalic Entertainment GmbH
        layout: left
        link: https://www.daedalic.com/
        link_text: daedalic.com
        sub_title: Internship
        caption: Feburary 2010
        description: |
          Research into expanding the game development toolchain using the Unreal Engine.

      - title: Airbus (EADS Innovation Works)
        layout: left
        link: https://www.airbus.com/en
        link_text: airbus.com
        sub_title: Internship
        caption: Feburary-September 2009
        description: >
          Research and development of an optimization software for simulated water
          distribution piping systems using C#.

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Wedding RSVP App
        link: https://gitlab.com/henning-private/wedding-rsvp
        description: >
          I'm getting married this year and wanted to do a completely digital invitation,
          so I started this project utilizing Googles Firebase and React.js.
      - layout: top-middle
        title: Analog Gauge Reader
        link: https://github.com/CaptainStandby/analog_gauge_reader
        description: >
          For my home automation project I wanted to monitor the flow and return flow
          temperature of the heating system in my home.
          The boiler has analog gauges only. I connected an IP Camera to a RaspberryPi
          to capture pictures of the gauges. Using image processing with OpenCV I
          implemented a service in Python to measure the displayed temperature. The
          measurements were then exposed via a Prometheus interface.

  - title: Skills
    layout: list
    content:
      - title: C# / .NET
        layout: left
        description: |
          Excellent knowledge and deep understanding of all aspects of the language and related techniques.
      - title: Typescript
        layout: left
        description: |
          Developed server side applications and customer facing SPAs.
      - title: Kubernetes
        layout: left
        description: |
          Designed and brought into production cloud native applications running on Kubernetes.
      - title: C / C++
        layout: left
        description: |
          Very good understanding of language and concepts.
      - title: Other Technologies, I have worked with
        layout: left
        description: >
          Terraform, Docker, Linux, Azure, AWS, GCP (Firebase), Vue.js, React.js, Python,
          Java, Kotlin, Kustomize, Infrastructure as Code, auth0, GraphQL

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Applied Sciences, Wedel, Germany
        caption: 2005 - 2009
        sub_title: Media Computer Science
        link: https://www.fh-wedel.de/studieren/international/incomings/
        link_text: fh-wedel.de
        quote: >
          The Fachhochschule Wedel University of Applied Sciences is a well-known private
          university with approximately 1.300 enrolled students located in the Hamburg
          Metropolitan Area in Northern Germany.
        description: |
          My primary fields of study were in computer graphics and virtual reality.

      # - layout: left
      #   title: Technisches Gymnasium, Hamburg, Germany
      #   caption: '2005'
      #   sub_title: Abitur (A Level)
        # description: |


  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in software engineering some of my other interests and hobbies are:
      - Hiking
      - Cycling
      - Cooking
      - and I'm a volunteer firefighter


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
